name: "McIntosh's"
favicon: null
layout_spectrum: 0.124442188302055
typography_spectrum: 0.6772791205439717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.331536547280848
  lightness: 0.6309380314778537
  saturation: 0.8613170082680881
  rhythmicContrast: 0.6445536040700972
purpose: []
